server:
  port: 9091

spring:
  datasource:
    driver-class-time: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/DBproductmicroservice
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true