server:
  port: 9092

spring:
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: sales-service
  datasource:
    driver-class-time: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/DBsalesmicroservice
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true