server:
  port: 9093

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: java4
    password: root
  zipkin:
    enabled: true
    base-url: http://10.76.2.233:9411
    service:
      name: userprofile-service
  data:
    mongodb:
      host: 34.132.20.108
      port: 27777
      database: Java4DB
      username: JavaUser
      password: Aa123456

myapplication:
  feignclient:
    elasticsearch: http://localhost:9100/userprofile